// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATszpniAlJIEg5_dOiXjw68PozXLENw9s',
    appId: '1:612113481876:web:754848b1ef6da2aafb7481',
    messagingSenderId: '612113481876',
    projectId: 'smart-panel-light-transformer',
    authDomain: 'smart-panel-light-transformer.firebaseapp.com',
    databaseURL: 'https://smart-panel-light-transformer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-panel-light-transformer.appspot.com',
    measurementId: 'G-HWEKDFQBYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxD-Ink_uiAAGfypR03R7i0AdY5U64sKg',
    appId: '1:612113481876:android:440d84cc5e3794c5fb7481',
    messagingSenderId: '612113481876',
    projectId: 'smart-panel-light-transformer',
    databaseURL: 'https://smart-panel-light-transformer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-panel-light-transformer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IOv_M8Vja3a5o97oChnLF3Sl-xkcR1I',
    appId: '1:612113481876:ios:6277779825d608b7fb7481',
    messagingSenderId: '612113481876',
    projectId: 'smart-panel-light-transformer',
    databaseURL: 'https://smart-panel-light-transformer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-panel-light-transformer.appspot.com',
    iosBundleId: 'com.example.smarthomeui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IOv_M8Vja3a5o97oChnLF3Sl-xkcR1I',
    appId: '1:612113481876:ios:6277779825d608b7fb7481',
    messagingSenderId: '612113481876',
    projectId: 'smart-panel-light-transformer',
    databaseURL: 'https://smart-panel-light-transformer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-panel-light-transformer.appspot.com',
    iosBundleId: 'com.example.smarthomeui',
  );
}
